parameters:
  - name: terraformVersion
    type: string
  - name: projectName
    type: string
  - name: backendAppFolder
    type: string
  - name: terraformFolder
    type: string
  - name: workingDirectory
    type: string
  - name: environments
    type: object

variables:
  workingDirectory: ${{parameters.workingDirectory}}
  terraformVersion: ${{parameters.terraformVersion}}
  projectName: ${{parameters.projectName}}
  backendAppFolder: ${{parameters.backendAppFolder}}
  terraformFolder: ${{parameters.terraformFolder}}
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

stages:
  - stage: plan
    displayName: Plan
    jobs:
      - ${{each environment in parameters.environments}}:
          - job: plan_${{environment.stage}}
            displayName: Plan ${{environment.stage}}
            steps:
              - script: |
                  echo "Terraform plan ;)"
                displayName: "Dummy script"
                workingDirectory: ${{parameters.workingDirectory}}

              # - template: steps/app-service-build-deploy.yaml
              #   parameters:
              #     environment: ${{environment}}

  - ${{each environment in parameters.environments}}:
      - stage: app_service_${{environment.stage}}
        condition: and(succeeded('plan'), eq(variables.isMain, 'true'))
        dependsOn: plan
        displayName: Deploy App Service ${{environment.stage}}
        jobs:
          - job: build_${{environment.stage}}
            displayName: Build ${{environment.stage}}
            steps:
              - template: steps/app-service-build-deploy.yaml
                parameters:
                  environment: ${{environment}}
          # - deployment:
          #   environment: ${{environment.environment}}
          #   strategy:
          #     runOnce:
          #       deploy:
          #         steps:
          #           - template: steps/app-service-build-deploy.yaml
          #             parameters:
          #               environment: ${{environment}}
