parameters:
  - name: terraformVersion
    type: string
  - name: projectName
    type: string
  - name: workingDirectory
    type: string
  - name: environments
    type: object

variables:
  workingDirectory: ${{parameters.workingDirectory}}
  terraformVersion: ${{parameters.terraformVersion}}
  projectName: ${{parameters.projectName}}
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

stages:
  - stage: plan
    displayName: Plan
    jobs:
      - ${{each environment in parameters.environments}}:
          - job: backend_${{environment.stage}}
            displayName: Backend ${{environment.stage}}
            steps:
              - template: steps/tfstate-rg.yaml
                parameters:
                  environment: ${{environment}}

          - job: plan_${{environment.stage}}
            displayName: Plan ${{environment.stage}}
            steps:
              - template: steps/environment-rg.yaml
                parameters:
                  environment: ${{environment}}

              # - template: steps/app-service-build-deploy.yaml
              #   parameters:
              #     environment: ${{environment}}

  - ${{each environment in parameters.environments}}:
      - stage: app_service_${{environment.stage}}
        condition: and(succeeded('plan'), eq(variables.isMain, 'true'))
        dependsOn: plan
        displayName: Deploy App Service ${{environment.stage}}
        jobs:
          - deployment:
            environment: ${{environment.environment}}
            strategy:
              runOnce:
                deploy:
                  steps:
                    - template: steps/dummy.yaml
                      parameters:
                        environment: ${{environment}}
          - job: build_${{environment.stage}}
            displayName: Build ${{environment.stage}}
            steps:
              - template: steps/app-service-build-deploy.yaml
                parameters:
                  environment: ${{environment}}
