trigger:
  paths:
    include:
      - backend/src*

pool:
  vmImage: ubuntu-latest

extends:
  template: ../pipeline-templates/environment-deploy.yaml
  parameters:
    terraformVersion: "1.3.6"
    projectName: nodejs-chat-orchestrator
    workingDirectory: $(System.DefaultWorkingDirectory)
    environments:
      - stage: dev
        serviceConnection: SC-AzureDevOps
        backendWebApp: backend-webapp-dev
        environment: dev
        backendDirectory: $(System.DefaultWorkingDirectory)/backend
        resourceGroup: nodejs-chat-orchestrator-tfstate-dev-rg
        resourceGroupLocation: eastus
        storageAccount: chatorchestratordev
