trigger:
  paths:
    include:
      - backend/src*

pool:
  vmImage: ubuntu-latest

extends:
  template: ../../pipeline-templates/environment-deploy.yaml
  parameters:
    terraformVersion: "1.3.6"
    projectName: nodejs-chat-orchestrator
    workingDirectory: $(System.DefaultWorkingDirectory)
    environments:
      - stage: dev
        serviceConnection: SC-AzureDevOps
        backendWebApp: backend-wa
        environment: dev
        backendDirectory: $(System.DefaultWorkingDirectory)/backend
        resourceGroup: nodejs-chat-orchestrator-tfstate-dev-rg
        resourceGroupLocation: eastus
        storageAccount: chatorchestratordev
# stages:
#   - stage: build
#     displayName: Build
#     jobs:
#       - job: build_dev
#         displayName: Build dev
#         steps:
#           - template: ../../pipeline-templates/steps/app-service-build.yaml
#             parameters:
#               workingDirectory: "$(System.DefaultWorkingDirectory)/backend"
#               serviceConnection: "SC-AzureDevOps"
#               webAppName: "sampleapp-lso1234"
