trigger:
    - main

variables:
    # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'SC-AzureDevOps'

    # Web app name
  webAppName: 'sampleapp-lso1234'

    # Environment name
  environmentName: 'dev'

    # Agent VM image name
  vmImageName: 'ubuntu-latest'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    displayName: Build
    jobs:
    - job: build_dev
      displayName: Build dev
      steps:
        - template: ../../pipeline-templates/steps/app-service-build.yaml
          parameters:
            workingDirectory: '$(System.DefaultWorkingDirectory)/backend'

    - job: deploy_dev
      displayName: Deploy dev
      steps:
        - template: ../../pipeline-templates/steps/app-service-deploy.yaml
          parameters:
            workingDirectory: '$(System.DefaultWorkingDirectory)/backend'
            serviceConnection: 'SC-AzureDevOps'
            webAppName: 'sampleapp-lso1234'
            packageFile: $(Pipeline.Workspace)/drop/$(Build.BuildId)