version: '3.3'
services:
  my-db:
    image: mysql:5.7
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      
  api:
    image: backend
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
      # args:
      #   - MYSQL_HOST=${MYSQL_HOST}
    volumes:
       - "./backend:/home/node/app"
    ports:
       - 3000:3000
    restart: "always"
    depends_on:
      - "my-db"
    # environment:
    #   MYSQL_HOST: ${MYSQL_HOST}
# Names our volume
volumes:
  my-db:
    driver: local

networks:
  my-db:
    driver: bridge