name: 'Terraform Plan'
description: "Performs the terraform plan"

inputs:
 # Credentials for deployment to AWS
  AWS_ACCESS_KEY_ID:
    description: "AWS access key"
    required: true
  AWS_SECRET_ACCESS_KEY: 
    description: "AWS secret key"
    required: true
  #AWS defaul region
  AWS_DEFAULT_REGION:
    description: "AWS secret key"
    required: false
    default: us-east-1
  # S3 bucket for the Terraform state
  BUCKET_TF_STATE: 
    description: "S3 bucket for the Terraform state"
    required: true
  #Terraform Version
  TERRAFORM_VERSION:
    description: "Terraform version"
    required: true
  STAGE:
    description: "Running stage"
    required: true

runs:
  using: "composite"
  steps:
  - name: Checkout
    uses: actions/checkout@v3

  - name: Setup Terraform with specified version on the runner
    uses: hashicorp/setup-terraform@v2
    with:
      terraform_version: ${{ inputs.TERRAFORM_VERSION }}

  - name: Copy ${{ inputs.STAGE }} plan from S3 
    shell: bash
    run: |
      aws s3 cp s3://$BUCKET_TF_STATE/plans/terraform-live-${{ inputs.STAGE }}-$GITHUB_RUN_NUMBER-$GITHUB_RUN_ID.tar terraform-live.tar
      tar -xvf terraform-live.tar -C ./
    env:
      AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION }}

  - name: Copy ${{ inputs.STAGE }} mdoules from S3 
    shell: bash
    run: |
      aws s3 cp s3://$BUCKET_TF_STATE/plans/terraform-modules-${{ inputs.STAGE }}-$GITHUB_RUN_NUMBER-$GITHUB_RUN_ID.tar terraform-modules.tar
      tar -xvf terraform-modules.tar -C ./
    env:
      AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION }}

  - name: Terraform Apply
    shell: bash
    run: 
      ls -ltr
    working-directory: ./terraform-live