apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend
        imagePullPolicy: IfNotPresent
        env:
          - name: PORT
            value: "8080"
        resources:
          limits:
            memory: 64Mi
            cpu: 128m
        ports:
        - containerPort: 8080
          name: http
