name: "List Dir"
description: "List dir command"

inputs:
  STAGE: 
    description: "Current state"
    required: true

runs:
  using: "composite"
  steps:
    - name: List dir
      shell: bash
      run: |
        echo ${{ inputs.STAGE }}