name: "List Dir"

inputs:
  version:
    required: true
  STAGE: 
    description: "Current state"
    required: true

runs:
  using: "composite"
  steps:
    - name: List dir
      run: |
        echo ${{ inputs.STAGE }}