name: 'Environment Deploy'
on:
  push:
    branches:
      - main

env:
 # Credentials for deployment to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #AWS defaul region
  AWS_DEFAULT_REGION: us-east-1
  # S3 bucket for the Terraform state
  BUCKET_TF_STATE: nodejs-chat-orchestrator-tfstate-s3

jobs:
  ReuseableMatrixJobForDeployment:
    strategy:
      matrix:
        target: [dev, stage, prod]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: "./.github/template/deploy/action.yml"
      with:
        STAGE: ${{ matrix.target }}