name: 'Environment Deploy'
on:
  push:
    branches:
      - main

env:
 # Credentials for deployment to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #AWS defaul region
  AWS_DEFAULT_REGION: us-east-1

jobs:
  plan:
    strategy:
      matrix:
        stage: [dev, prod]
    runs-on: ubuntu-latest
    defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.
       working-directory: aws/terraform-live
    concurrency: ${{ matrix.stage }}
    steps:
    - uses: actions/checkout@v3
    # - uses: "./.github/template/deploy/action.yaml"
    #   with:
    #     STAGE: ${{ matrix.target }}
    # - uses: "./.github/actions/deploy"
    #   with:
    #     STAGE: ${{ matrix.stage }}
    - uses: "./.github/actions/terraform-plan"
      with:
        BUCKET_TF_STATE: s3-nodejs-chat-orchestrator-tfstate-${{ matrix.stage }}
        STAGE: ${{ matrix.stage }}
        WORKING_DIR: ./aws

  apply:
    needs: plan
    strategy:
      matrix:
        stage: [dev, prod]
    runs-on: ubuntu-latest
    environment: ${{ matrix.stage }}
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - uses: "./.github/actions/terraform-apply"
      with:
        BUCKET_TF_STATE: s3-nodejs-chat-orchestrator-tfstate-${{ matrix.stage }}
        STAGE: ${{ matrix.stage }}